# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"
#    ignore:
#      - dependency-name: infection/infection
#        versions:
#          - ">= 0"
#      - dependency-name: phpunit/phpunit
#        versions:
#          - ">= 0"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/browscap/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/browscap"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/browser-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/browser-detector"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/curated/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/curated"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/donatj/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/donatj"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/endorphin/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/endorphin"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/matomo/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/matomo"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/sinergi/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/sinergi"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/ua-parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/ua-parser"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/ua-parser-js"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/whichbrowser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/whichbrowser"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/woothee/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/woothee"
    rebase-strategy: "auto"

  - package-ecosystem: "composer"
    directory: "tests/zsxsoft/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/zsxsoft"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "tests/ua-parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/tests/ua-parser"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "tests/ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/tests/ua-parser-js"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "parsers/3rd-eden-useragent-js-2/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/3rd-eden-useragent-js-2"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "parsers/bowser-js-2/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/bowser-js-2"
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "parsers/browser-detect-js-0/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/browser-detect-js-0"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
    ignore:
      - dependency-name: "mimmi20/ci"
    rebase-strategy: "auto"
