# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Base directory

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"
#    ignore:
#      - dependency-name: infection/infection
#        versions:
#          - ">= 0"
#      - dependency-name: phpunit/phpunit
#        versions:
#          - ">= 0"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm"

  # tests
  - package-ecosystem: "composer"
    directory: "tests/browscap/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/browscap"

  - package-ecosystem: "composer"
    directory: "tests/browser-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/browser-detector"

  - package-ecosystem: "composer"
    directory: "tests/cbschuld/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/cbschuld"

  - package-ecosystem: "composer"
    directory: "tests/crawler-detect/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/crawler-detect"

  - package-ecosystem: "composer"
    directory: "tests/curated/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/curated"

  - package-ecosystem: "composer"
    directory: "tests/donatj/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/donatj"

  - package-ecosystem: "composer"
    directory: "tests/endorphin/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/endorphin"

  - package-ecosystem: "composer"
    directory: "tests/matomo/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/matomo"

  - package-ecosystem: "composer"
    directory: "tests/mobile-detect/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/mobile-detect"

  - package-ecosystem: "composer"
    directory: "tests/sinergi/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/sinergi"

  - package-ecosystem: "composer"
    directory: "tests/ua-parser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/ua-parser-js"

  - package-ecosystem: "composer"
    directory: "tests/ua-parser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/ua-parser-php"

  - package-ecosystem: "composer"
    directory: "tests/whichbrowser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/whichbrowser-php"

  - package-ecosystem: "composer"
    directory: "tests/woothee-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/woothee-php"

  - package-ecosystem: "composer"
    directory: "tests/zsxsoft/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/tests/zsxsoft"

  - package-ecosystem: "npm"
    directory: "tests/ua-parser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/tests/ua-parser-js"

  # parsers
  - package-ecosystem: "npm"
    directory: "parsers/3rd-eden-useragent/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/3rd-eden-useragent"

  - package-ecosystem: "npm"
    directory: "parsers/amplitude-ua-parser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/amplitude-ua-parser-js"

  - package-ecosystem: "npm"
    directory: "parsers/bowser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/bowser"

  - package-ecosystem: "npm"
    directory: "parsers/bowser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/bowser"

  - package-ecosystem: "composer"
    directory: "parsers/browscap-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/browscap-php"

  - package-ecosystem: "npm"
    directory: "parsers/browser-detect/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/browser-detect"

  - package-ecosystem: "composer"
    directory: "parsers/browser-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/browser-detector"

  - package-ecosystem: "composer"
    directory: "parsers/cbschuld/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/cbschuld"

  - package-ecosystem: "composer"
    directory: "parsers/crawler-detect/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/crawler-detect"

  - package-ecosystem: "npm"
    directory: "parsers/detect-browser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/detect-browser"

  - package-ecosystem: "npm"
    directory: "parsers/device-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/device-detector"

  - package-ecosystem: "npm"
    directory: "parsers/device-detector-node/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/device-detector-node"

  - package-ecosystem: "composer"
    directory: "parsers/donatj/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/donatj"

  - package-ecosystem: "composer"
    directory: "parsers/endorphin/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/endorphin"

  - package-ecosystem: "npm"
    directory: "parsers/express-useragent/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/express-useragent"

  - package-ecosystem: "npm"
    directory: "parsers/fex-uadevice/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/fex-uadevice"

  - package-ecosystem: "npm"
    directory: "parsers/financial-times-useragent_parser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/financial-times-useragent_parser"

  - package-ecosystem: "npm"
    directory: "parsers/hotoo-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/hotoo-detector"

  - package-ecosystem: "composer"
    directory: "parsers/jenssegers-agent/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/jenssegers-agent"

  - package-ecosystem: "npm"
    directory: "parsers/journyio-user-agent-parser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/journyio-user-agent-parser"

  - package-ecosystem: "composer"
    directory: "parsers/matomo/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/matomo"

  - package-ecosystem: "composer"
    directory: "parsers/mobile-detect/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/mobile-detect"

  - package-ecosystem: "npm"
    directory: "parsers/node-device-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/node-device-detector"

  - package-ecosystem: "npm"
    directory: "parsers/platformjs/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/platformjs"

  - package-ecosystem: "composer"
    directory: "parsers/sinergi/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/sinergi"

  - package-ecosystem: "npm"
    directory: "parsers/ua-parser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/ua-parser-js"

  - package-ecosystem: "composer"
    directory: "parsers/ua-parser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/ua-parser-php"

  - package-ecosystem: "npm"
    directory: "parsers/vigour-ua/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/vigour-ua"

  - package-ecosystem: "npm"
    directory: "parsers/whichbrowser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/whichbrowser-js"

  - package-ecosystem: "composer"
    directory: "parsers/whichbrowser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/whichbrowser-php"

  - package-ecosystem: "composer"
    directory: "parsers/wolfcast/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/wolfcast"

  - package-ecosystem: "npm"
    directory: "parsers/woothee-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm/parsers/woothee-js"

  - package-ecosystem: "composer"
    directory: "parsers/woothee-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/woothee-php"

  - package-ecosystem: "composer"
    directory: "parsers/zsxsoft/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "composer/parsers/zsxsoft"

  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
