# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

multi-ecosystem-groups:
  maintenance-master:
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    versioning-strategy: "increase"

    rebase-strategy: "disabled"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

updates:
  - package-ecosystem: "composer"

    directories:
      - "/"
      - "tests/browscap/"
      - "tests/browser-detector/"
      - "tests/cbschuld/"
      - "tests/crawler-detect/"
      - "tests/curated/"
      - "tests/donatj/"
      - "tests/endorphin/"
      - "tests/matomo/"
      - "tests/mobile-detect/"
      - "tests/ua-parser-js/"
      - "tests/ua-parser-php/"
      - "tests/whichbrowser-php/"
      - "tests/woothee-php/"
      - "parsers/agent-zero/"
      - "parsers/browscap-php/"
      - "parsers/browser-detector/"
      - "parsers/cbschuld/"
      - "parsers/crawler-detect/"
      - "parsers/donatj/"
      - "parsers/endorphin/"
      - "parsers/foroco/"
      - "parsers/fyre-useragent/"
      - "parsers/jenssegers-agent/"
      - "parsers/matomo/"
      - "parsers/mobile-detect/"
      - "parsers/platine-php/"
      - "parsers/ua-parser-php/"
      - "parsers/whichbrowser-php/"
      - "parsers/wolfcast/"
      - "parsers/woothee-php/"

    multi-ecosystem-group: "maintenance-master"

    patterns: [ "*" ]

  - package-ecosystem: "npm"

    directories:
      - "/"
      - "tests/ua-parser-js/"
      - "parsers/amplitude-ua-parser-js/"
      - "parsers/bowser/"
      - "parsers/browser-detect/"
      - "parsers/detect-browser/"
      - "parsers/device-detector/"
      - "parsers/device-detector-node/"
      - "parsers/express-useragent/"
      - "parsers/fex-uadevice/"
      - "parsers/financial-times-useragent_parser/"
      - "parsers/hotoo-detector/"
      - "parsers/journyio-user-agent-parser/"
      - "parsers/node-device-detector/"
      - "parsers/platformjs/"
      - "parsers/ua-parser-js/"
      - "parsers/vigour-ua/"
      - "parsers/whichbrowser-js/"
      - "parsers/woothee-js/"

    multi-ecosystem-group: "maintenance-master"

    patterns: [ "*" ]

  - package-ecosystem: "github-actions"

    directory: "/"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    multi-ecosystem-group: "maintenance-master"

    patterns: [ "*" ]
